// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// True inside AERA Recovery, false on a PC.
bool inRecovery() => RustLib.instance.api.crateApiAeraInRecovery();

/// AERA's selected language, such as `de_DE`.
String recoveryLocale() => RustLib.instance.api.crateApiAeraRecoveryLocale();

StorageDirs storageDirs() => RustLib.instance.api.crateApiAeraStorageDirs();

Future<DeviceInfo> deviceInfo() =>
    RustLib.instance.api.crateApiAeraDeviceInfo();

/// Plays a sine tone through the phone's speaker. Returns once the bridge
/// has taken the samples. Fails on a PC, where there is no AERA audio bridge.
Future<void> playTone({
  required double frequencyHz,
  required int milliseconds,
  required double volume,
}) => RustLib.instance.api.crateApiAeraPlayTone(
  frequencyHz: frequencyHz,
  milliseconds: milliseconds,
  volume: volume,
);

/// Plays interleaved 48 kHz stereo 16-bit samples through the speaker.
Future<void> playPcm({required List<int> samples}) =>
    RustLib.instance.api.crateApiAeraPlayPcm(samples: samples);

class DeviceInfo {
  final String kernel;
  final String machine;
  final int cpuCount;
  final BigInt totalRamBytes;
  final BigInt freeRamBytes;
  final BigInt uptimeSeconds;

  const DeviceInfo({
    required this.kernel,
    required this.machine,
    required this.cpuCount,
    required this.totalRamBytes,
    required this.freeRamBytes,
    required this.uptimeSeconds,
  });

  @override
  int get hashCode =>
      kernel.hashCode ^
      machine.hashCode ^
      cpuCount.hashCode ^
      totalRamBytes.hashCode ^
      freeRamBytes.hashCode ^
      uptimeSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          kernel == other.kernel &&
          machine == other.machine &&
          cpuCount == other.cpuCount &&
          totalRamBytes == other.totalRamBytes &&
          freeRamBytes == other.freeRamBytes &&
          uptimeSeconds == other.uptimeSeconds;
}

class StorageDirs {
  /// Private, survives reboots.
  final String appData;

  /// Shared with the user as `/sdcard/AERA/Downloads`.
  final String downloads;

  /// In RAM, cleared when the app closes.
  final String temp;

  const StorageDirs({
    required this.appData,
    required this.downloads,
    required this.temp,
  });

  @override
  int get hashCode => appData.hashCode ^ downloads.hashCode ^ temp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageDirs &&
          runtimeType == other.runtimeType &&
          appData == other.appData &&
          downloads == other.downloads &&
          temp == other.temp;
}
