// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fade`

/// Plays notes one after another as a single stream, so they never overlap.
Future<void> playNotes({
  required List<double> frequenciesHz,
  required int noteMilliseconds,
  required double volume,
}) => RustLib.instance.api.crateApiSoundPlayNotes(
  frequenciesHz: frequenciesHz,
  noteMilliseconds: noteMilliseconds,
  volume: volume,
);
